### ISSUE TITLE
library.find_compatible_macros is not a function

### ISSUE THREAD

**Issue by inf3rno** [acuminous/yadda#195]
I have the `TypeError: library.find_compatible_macros is not a function` exception by running yadda with mocha. What does it mean?

I am trying to create an example app with basic math. The tests were ok with cucumberjs.

```cucumber
  Scenario: Addition of numbers
    Given I have multiple numbers
    When I add these numbers together
    Then I should get their sum as result
```

```js
var English = require("yadda").localisation.English,
    math = require("../../index"),
    assert = require("assert");

module.exports = function () {

    var lib = English.library();

    lib.given(/^I have (\w+) numbers$/, function (count, next) {
        this.numbers = [];
        var l = 2;
        if (count == "multiple")
            l = randomInteger(3, 10);
        for (var i = 0; i < l; ++i)
            this.numbers[i] = randomInteger(-100, 100);
        next();
    });

    lib.when(/^I (\w+) .* numbers? .*$/, function (operatorName, next) {
        if (!math.hasOwnProperty(operatorName))
            throw new Error("Operator is not supported by the math lib: " + operatorName);
        this.operator = math[operatorName];
        this.result = this.operator.apply(math, this.numbers);
        next();
    });

    lib.then(/^I should get their (\w+) as result$/, function (resultType, next) {
        var expectedAlgorithms = {
            sum: function (a, b) {
                return a + b;
            },
            product: function (a, b) {
                return a * b;
            },
            difference: function (a, b) {
                return a - b;
            },
            quotient: function (a, b) {
                return a / b;
            }
        };
        if (!expectedAlgorithms.hasOwnProperty(resultType))
            throw new Error("Expectation about the result does not match with any known expectation.");
        var expectedAlgorithm = expectedAlgorithms[resultType];
        var expectedResult = this.numbers[0];
        for (var i = 1, l = this.numbers.length; i < l; ++i)
            expectedResult = expectedAlgorithm(expectedResult, this.numbers[i]);
        assert.strictEqual(this.result, expectedResult, "The actual and the expected results are not the same.");
        next();
    });
    return lib;
};

var randomInteger = function (min, max) {
    if (isNaN(min) || isNaN(max) || min % 1 || max % 1)
        throw new Error("Min and max must be integers.");
    return min + Math.floor(Math.random() * (max - min + 1));
};
```

```
  1) Arithmetic operators Addition of numbers Given I have multiple numbers:
     TypeError: library.find_compatible_macros is not a function
      at D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\Interpreter.js:83:42
      at Array.inject (D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\Array.js:109:22)
      at Array.inject (D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\fn.js:27:23)
      at compatible_macros (D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\Interpreter.js:82:26)
      at rank_macros (D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\Interpreter.js:78:38)
      at D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\Interpreter.js:42:26
      at Array.collect (D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\Array.js:87:26)
      at Array.collect (D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\fn.js:27:23)
      at validate (D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\Interpreter.js:41:35)
      at yadda (D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\Yadda.js:40:26)
      at yadda (D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\Yadda.js:39:85)
      at D:\creation\software developer\projects\javascript-project-template\yadda.conf.js:13:23
      at D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\plugins\mocha\StepLevelPlugin.js:55:17
      at Context.<anonymous> (D:\creation\software developer\projects\javascript-project-template\node_modules\yadda\lib\plugins\mocha\BasePlugin.js:55:13)
      at callFnAsync (D:\creation\software developer\projects\javascript-project-template\node_modules\mocha\lib\runnable.js:338:8)
      at Test.Runnable.run (D:\creation\software developer\projects\javascript-project-template\node_modules\mocha\lib\runnable.js:290:7)
      at Runner.runTest (D:\creation\software developer\projects\javascript-project-template\node_modules\mocha\lib\runner.js:422:10)
      at D:\creation\software developer\projects\javascript-project-template\node_modules\mocha\lib\runner.js:533:12
      at next (D:\creation\software developer\projects\javascript-project-template\node_modules\mocha\lib\runner.js:342:14)
      at D:\creation\software developer\projects\javascript-project-template\node_modules\mocha\lib\runner.js:352:7
      at next (D:\creation\software developer\projects\javascript-project-template\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (D:\creation\software developer\projects\javascript-project-template\node_modules\mocha\lib\runner.js:320:5)
```

It throws the exception by the givens and every other step is pending after that.

**Comment by inf3rno** [comment]
I managed to fix it, the problem was that it required the library instance instead of the factory function. This is a difference between cucumber and yadda. Another problem was that this.[numbers, operator, results] does not work by yadda.

**Comment by cressie176** [comment]
Glad you got it sorted. If you want to store state checkout the context section of the github user guide.

**Comment by inf3rno** [comment]
@cressie176 Does this work only with the `ctx` property?

**Comment by cressie176** [comment]
No, whatever is in the 2nd argument to createInstance will be bound do the the step at invocation.

**Comment by ZHChen8397** [comment]
@inf3rno  I wonder what is 'required the library instance instead of the factory function' mean?
I encounter the same problem when I try to run my test with if condition.
something like
`if(some condition){
   module.exports = English.library()
  .given('...', function () {
    // do something
  })
  .when('...', function () {
    // do something
  })
  .then('...', function (num) {
    // do something
  })}`
